### ISSUE TITLE
Thoughts on v0.1.3 and naming

### ISSUE THREAD

**Issue by vancluever** [paybyphone/terraform_aws_vpc#1]
Hello PBP team!

Just saw the changelog for v0.1.3, and I think adding the `Name` tag (I'm guessing so that things show up nicely in the console) is a great idea!

Just had some feedback:

 * Maybe it would be a good idea to have just a single field - `name`, or `vpc_name` - and prepend that to everything? Examples:
 * `aws_vpc.vpc` - `Name` would be **Sample VPC**
 * `aws_subnet.public_subnets` - `Name` would be **Sample VPC - Public Subnet (ca-central-1a)**
 * `aws_route_table.public_route_table` - `Name` would be **Sample VPC - Public Route Table**

This would eliminate the need for anyone to look at any other field other than the name in the console to get an immediate idea what VPC the subnets or route tables belonged to (which is what I'm guessing the idea of this PR is).

Also - I kind of wonder if `public_subnet_name_prefix` is needed in this regard, as just from face value I'm wondering if it really presents much extra value - considering the defaults subnet prefix, and a named VPC, you get:

 * The VPC would end up being named something like **Sample VPC**
 * And its subnets would end up being named something like **Public - A** and **Public - B**

To me, that seems a little disjointed - I would still need to trace the VPC ID to know what the name of that VPC was.

The last issue I see with the above is that I think there's probably more value to use the full AZ name versus a short-form (even if it turns out to be longer).

Anyway, just some thoughts, and otherwise take care! :slightly_smiling_face:

**Comment by gdavison** [comment]
Thanks for the feedback. We did some thinking back and forth on the naming, whether it should be full names or not. In practice, it seems clear enough, especially with how the AWS console fills in names in some columns in addition to the ID when a name is set.
And, of course, if it becomes an issue, fixing it is a "simple" terraform run! :)

**Comment by vancluever** [comment]
Hey @gdavison - fair enough. I just thought I'd send along my thoughts and suggestions 🙂
